"""
Django settings for tigray_genocide project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/n/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from tigray_genocide.cache_headers import add_whitenoise_cache_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7_x5(j(l5mbrt6%g(f0r02j2&bhu%2%ws4d^x*$gmx-wgek92j'

# SECURITY WARNING: don't run with debug turned on in production!
_default_debug = 'True' if {'runserver', 'test'}.intersection(sys.argv) else 'False'
DEBUG = os.environ.get('DJANGO_DEBUG', _default_debug).lower() in {
    '1',
    'true',
    'yes',
    'on',
}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'tigraygenocide.com,www.tigraygenocide.com,localhost,127.0.0.1,[::1],testserver',
    ).split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'App',
    'django_summernote',
    'captcha',
    'django.contrib.humanize',
    'import_export',
]

CAPTCHA_FONT_SIZE = 40
CAPTCHA_IMAGE_SIZE = (150, 50)
CAPTCHA_FOREGROUND_COLOR = '#001F3F'
CAPTCHA_BACKGROUND_COLOR = '#FFFFFF'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'tigray_genocide.cache_headers.MediaCacheControlMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')



ROOT_URLCONF = 'tigray_genocide.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tigray_genocide.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tigray_genocide',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# settings.py

LOGIN_URL = '/Adminstrator-login-page/'
LOGIN_REDIRECT_URL = '/Admin-dashboard/'

EMAIL_BACKEND = 'App.email_backend.DatabasePasswordEmailBackend'
EMAIL_HOST = 'mail.tigraygenocide.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'tigraygenocide@tigraygenocide.com'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL = True

RECAPTCHA_PUBLIC_KEY = '6LfhhCspAAAAAIDS8i87B1LMcnmRwK2eUzv_2H71'
RECAPTCHA_PRIVATE_KEY = '6LfhhCspAAAAAFBxuITDIweCuUAhJxBeAiv0htDd'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Non-fingerprinted static files may change without their URL changing, so they
# receive a shorter cache lifetime. Fingerprinted files are overridden to one
# year and marked immutable by add_whitenoise_cache_headers().
WHITENOISE_MAX_AGE = 604800
WHITENOISE_ADD_HEADERS_FUNCTION = add_whitenoise_cache_headers

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Public homepage HTML can be reused briefly while still surfacing updates
# within five minutes.
PUBLIC_HTML_CACHE_SECONDS = int(
    os.environ.get('PUBLIC_HTML_CACHE_SECONDS', '300')
)

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


PLOTLY_LOGO = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
