# Generated by Django 5.0.1 on 2026-07-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0095_homepage_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='civilian_victims',
            new_name='App_civilia_approva_9eefa3_idx',
            old_name='App_civilia_approva_7ef319_idx',
        ),
        migrations.RenameIndex(
            model_name='unverified_civilian',
            new_name='App_unverif_zone_444ca2_idx',
            old_name='App_unverif_zone_3dfb90_idx',
        ),
    ]
