# Generated by Django 6.0.2 on 2026-08-03 13:02

import App.fields
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0100_video_archive_date_created_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis_articles',
            name='id',
            field=App.fields.Char32UUIDField(default=uuid.uuid4, editable=False, help_text='Automatically generated unique ID for this article.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='id',
            field=App.fields.Char32UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo_archive',
            name='id',
            field=App.fields.Char32UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unverified_civilian',
            name='id',
            field=App.fields.Char32UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video_archive',
            name='id',
            field=App.fields.Char32UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='id',
            field=App.fields.Char32UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
